### ISSUE TITLE
这个是手机小游戏 世界ol 的客户端还是服务端?

### ISSUE THREAD

**Issue by liaohui5** [treefuture/World-Online#3]
可以直接用 docker 部署吗?想自己部署一下, 整个单机玩玩, 怀念下童年

**Comment by treefuture** [comment]
这个只是一个游戏的辅助网站，而且这个写的很low，不是游戏

**Comment by treefuture** [comment]
> 可以直接用码头部署吗？想自己部署一下，整个单机玩玩，怀念下童年

这个只是一个游戏的辅助网站，而且这个写的很低，不是游戏。这个是谷徳的游戏，现在还在运营。想玩儿可以去官网下载试试
游戏官网：http://sj.good321.net/​

**Comment by hitoxiao** [comment]
有私服就好了

**Comment by liaohui5** [comment]
> 有私服就好了

没有也无所谓了, 时间总是一去不回, 现在认识了新的朋友, 一起玩玩其他游戏也挺好
